### ISSUE TITLE
License Violation

### ISSUE THREAD

**Issue by Gottox** [mrgreen3/springlinux#1]
1. Please add the [COPYING](https://github.com/voidlinux/void-mklive/blob/master/COPYING) file from [void-mklive](https://github.com/voidlinux/void-mklive) if you copy the source of this project.

2. Read *AND* understand the [license](https://github.com/voidlinux/void-mklive/blob/master/COPYING) before you fork a project.

**Comment by mrgreen3** [comment]
Added

On Monday, May 11, 2015, Enno Boland <notifications@github.com> wrote:

>
>    1.
>
>    Please add the COPYING
>    <https://github.com/voidlinux/void-mklive/blob/master/COPYING> file
>    from void-mklive <https://github.com/voidlinux/void-mklive> if you
>    copy the source of this project.
>    2.
>
>    Read *AND* understand the license
>    <https://github.com/voidlinux/void-mklive/blob/master/COPYING> before
>    you fork a project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrgreen3/springlinux/issues/1>.
>


-- 
Kev
